name: Build Veyon Chat Plugin for Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  VEYON_TAG: v4.9.7
  QT_VERSION: 6.8.3
  QT_ARCH: win64_msvc2022_64

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Qt (Qt 6 with modules)
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          python -m pip install aqtinstall

          # Install Qt 6 + needed modules
          python -m aqt install-qt windows desktop $env:QT_VERSION $env:QT_ARCH
          python -m aqt install-module windows desktop $env:QT_VERSION $env:QT_ARCH `
            qtimageformats qtshadertools qt5compat qtmultimedia

          # Log the available Qt modules for troubleshooting
          python -m aqt list-qt windows desktop --modules $env:QT_VERSION $env:QT_ARCH

          $QtPath = "$env:GITHUB_WORKSPACE\$env:QT_VERSION\msvc2022_64"
          echo "Qt6_DIR=$QtPath\lib\cmake\Qt6" >> $env:GITHUB_ENV
          echo "$QtPath\bin" >> $env:GITHUB_PATH

          # Quick sanity check so failures are obvious
          if (-not (Test-Path "$QtPath\lib\cmake\Qt6Multimedia\Qt6MultimediaConfig.cmake")) {
            Write-Error "Qt Multimedia module not found at $QtPath"; exit 1
          }

      - name: Fetch Veyon ${{ env.VEYON_TAG }} headers
        shell: powershell
        run: |
          git clone --depth 1 --branch $env:VEYON_TAG https://github.com/veyon/veyon.git veyon-src
          $root = Join-Path $pwd 'veyon-src'
          if (-not (Test-Path "$root/plugins") -and -not (Test-Path "$root/src/plugins")) {
            Write-Error "Unexpected Veyon layout at $root (no plugins/ or src/plugins/)"; exit 1
          }
          echo "VEYON_SRC_DIR=$root" >> $env:GITHUB_ENV
          Write-Host "Set VEYON_SRC_DIR=$root"

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        shell: powershell
        run: |
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_PREFIX_PATH="$env:GITHUB_WORKSPACE\$env:QT_VERSION\msvc2022_64" `
            -DQt6_DIR="$env:Qt6_DIR" `
            -DVEYON_SRC_DIR="$env:VEYON_SRC_DIR" `
            -DQT_DEBUG_FIND_PACKAGE=ON `
            ..

      - name: Build plugin
        shell: powershell
        run: |
          cd build
          cmake --build . --config Release --parallel

      - name: Prepare release-package
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path "release-package" -Force | Out-Null
          $dll = Get-ChildItem -Recurse build -Filter veyon-chat-plugin.dll | Select-Object -First 1
          if (-not $dll) { Write-Error "DLL not found"; exit 1 }
          Copy-Item $dll.FullName "release-package\veyon-chat-plugin.dll"
          $installScript = @(
            '@echo off',
            'echo Installing Veyon Chat Plugin...',
            'if not exist "C:\Program Files\Veyon\plugins" mkdir "C:\Program Files\Veyon\plugins"',
            'copy /Y veyon-chat-plugin.dll "C:\Program Files\Veyon\plugins\"',
            'echo Done. Restart Veyon Master/Service.'
          )
          Set-Content -Path "release-package\install.bat" -Value $installScript -Encoding ASCII
          $readme = @(
            '# Veyon Chat Plugin - Windows (for Veyon 4.9.7)',
            '',
            '1) Run `install.bat` as Administrator',
            '2) Restart **Veyon Service** (clients) and **Veyon Master** (teacher)',
            '3) Open Veyon and verify the plugin appears under Plugins'
          )
          Set-Content -Path "release-package\README.txt" -Value $readme -Encoding UTF8
          Compress-Archive -Path "release-package\*" -DestinationPath "veyon-chat-plugin-windows.zip" -Force

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: veyon-chat-plugin-windows
          path: |
            release-package/veyon-chat-plugin.dll
            release-package/install.bat
            release-package/README.txt
            veyon-chat-plugin-windows.zip
          retention-days: 90
