name: Build Veyon Chat Plugin for Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtmultimedia'
        
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '2023.04.15'
        
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake
      run: |
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_PREFIX_PATH="${env:Qt5_Dir}" `
          ..
      
    - name: Build plugin
      run: |
        cd build
        cmake --build . --config Release --parallel
        
    - name: Verify DLL creation
      run: |
        if (Test-Path "build/Release/veyon-chat-plugin.dll") {
          Write-Host "✅ DLL created successfully!"
          Get-Item "build/Release/veyon-chat-plugin.dll" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ DLL not found!"
          exit 1
        }
      shell: powershell
      
    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: veyon-chat-plugin-windows
        path: |
          build/Release/veyon-chat-plugin.dll
          install-windows.bat
          install-windows.ps1
          README.md
        retention-days: 30
        
    - name: Create release package
      run: |
        mkdir release-package
        Copy-Item "build/Release/veyon-chat-plugin.dll" "release-package/"
        Copy-Item "install-windows.bat" "release-package/"
        Copy-Item "install-windows.ps1" "release-package/"
        Copy-Item "README.md" "release-package/"
        Copy-Item "WINDOWS_INSTALLATION.md" "release-package/" -ErrorAction SilentlyContinue
        Compress-Archive -Path "release-package/*" -DestinationPath "veyon-chat-plugin-windows.zip"
      shell: powershell
      
    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: veyon-chat-plugin-release-package
        path: veyon-chat-plugin-windows.zip
        retention-days: 90
