name: Build Veyon Chat Plugin for Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup Qt
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        python -m pip install aqtinstall
        python -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 -m qtmultimedia
        $QtPath = "$env:GITHUB_WORKSPACE\5.15.2\msvc2019_64"
        echo "Qt5_DIR=$QtPath\lib\cmake\Qt5" >> $env:GITHUB_ENV
        echo "$QtPath\bin" >> $env:GITHUB_PATH
        if (Test-Path "$QtPath\bin\qmake.exe") {
          Write-Host "Qt installed successfully"
          & "$QtPath\bin\qmake.exe" -version
        } else {
          Write-Host "Qt installation failed"
          exit 1
        }
        
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake
      shell: powershell
      run: |
        cd build
        $QtDir = $env:Qt5_DIR
        Write-Host "Using Qt5_DIR: $QtDir"
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DQt5_DIR="$QtDir" -DCMAKE_PREFIX_PATH="$env:GITHUB_WORKSPACE\5.15.2\msvc2019_64" ..
      
    - name: Build plugin
      run: |
        cd build
        cmake --build . --config Release --parallel
        
    - name: Verify DLL creation
      shell: powershell
      run: |
        $dllPath = "build/Release/veyon-chat-plugin.dll"
        if (Test-Path $dllPath) {
          Write-Host "DLL created successfully!"
          Get-Item $dllPath | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "DLL not found!"
          Get-ChildItem -Recurse build | Where-Object {$_.Extension -eq ".dll"}
          exit 1
        }
      
    - name: Create installation files
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path "release-package" -Force
        Copy-Item "build/Release/veyon-chat-plugin.dll" "release-package/"
        
    - name: Create install script
      shell: powershell
      run: |
        echo '@echo off' > release-package/install.bat
        echo 'echo Installing Veyon Chat Plugin...' >> release-package/install.bat
        echo 'if not exist "C:\Program Files\Veyon\plugins" mkdir "C:\Program Files\Veyon\plugins"' >> release-package/install.bat
        echo 'copy veyon-chat-plugin.dll "C:\Program Files\Veyon\plugins\"' >> release-package/install.bat
        echo 'echo Plugin installed successfully!' >> release-package/install.bat
        echo 'echo Please restart Veyon Master and Service.' >> release-package/install.bat
        echo 'pause' >> release-package/install.bat
        
    - name: Create README
      shell: powershell
      run: |
        echo '# Veyon Chat Plugin - Windows Release' > release-package/README.txt
        echo '' >> release-package/README.txt
        echo '## Installation Instructions' >> release-package/README.txt
        echo '' >> release-package/README.txt
        echo '1. Extract all files to a folder' >> release-package/README.txt
        echo '2. Right-click install.bat and select Run as administrator' >> release-package/README.txt
        echo '3. Restart Veyon Master application' >> release-package/README.txt
        echo '4. Press F10 to open chat window' >> release-package/README.txt
        echo '' >> release-package/README.txt
        echo '## Files Included' >> release-package/README.txt
        echo '' >> release-package/README.txt
        echo '- veyon-chat-plugin.dll - The plugin file' >> release-package/README.txt
        echo '- install.bat - Automated installation script' >> release-package/README.txt
        echo '' >> release-package/README.txt
        echo '## Requirements' >> release-package/README.txt
        echo '' >> release-package/README.txt
        echo '- Veyon 4.9.7 installed' >> release-package/README.txt
        echo '- Windows 10/11' >> release-package/README.txt
        echo '- Administrator privileges for installation' >> release-package/README.txt
        
    - name: Create ZIP package
      shell: powershell
      run: |
        Compress-Archive -Path "release-package/*" -DestinationPath "veyon-chat-plugin-windows.zip" -Force
        
    - name: Upload plugin artifacts
      uses: actions/upload-artifact@v4
      with:
        name: veyon-chat-plugin-windows
        path: |
          release-package/veyon-chat-plugin.dll
          release-package/install.bat
          release-package/README.txt
        retention-days: 90
        
    - name: Upload complete package
      uses: actions/upload-artifact@v4
      with:
        name: veyon-chat-plugin-complete-package
        path: veyon-chat-plugin-windows.zip
        retention-days: 90
