name: Build Veyon Chat Plugin for Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  VEYON_TAG: v4.9.7

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Qt (5.15.2, MSVC2019 x64)
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          python -m pip install aqtinstall
          python -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64
          $QtPath = "$env:GITHUB_WORKSPACE\5.15.2\msvc2019_64"
          echo "Qt5_DIR=$QtPath\lib\cmake\Qt5" >> $env:GITHUB_ENV
          echo "$QtPath\bin" >> $env:GITHUB_PATH
          & "$QtPath\bin\qmake.exe" -version

      - name: Fetch Veyon 4.9.7 headers
        shell: powershell
        run: |
          git clone --depth 1 --branch $env:VEYON_TAG https://github.com/veyon/veyon.git veyon-src
          if (-not (Test-Path "veyon-src/src/plugins")) { Write-Error "Unexpected Veyon layout"; exit 1 }
          echo "VEYON_SOURCE_DIR=$env:GITHUB_WORKSPACE\veyon-src" >> $env:GITHUB_ENV

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        shell: powershell
        run: |
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DQt5_DIR="$env:Qt5_DIR" `
            -DCMAKE_PREFIX_PATH="$env:GITHUB_WORKSPACE\5.15.2\msvc2019_64" `
            -DVEYON_SOURCE_DIR="$env:VEYON_SOURCE_DIR" `
            ..

      - name: Build plugin
        shell: powershell
        run: |
          cd build
          cmake --build . --config Release --parallel

      - name: Prepare release-package
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path "release-package" -Force | Out-Null
          $dll = Get-ChildItem -Recurse build -Filter veyon-chat-plugin.dll | Select-Object -First 1
          if (-not $dll) { Write-Error "DLL not found"; exit 1 }
          Copy-Item $dll.FullName "release-package\veyon-chat-plugin.dll"
          $installScript = @(
            '@echo off',
            'echo Installing Veyon Chat Plugin...',
            'if not exist "C:\Program Files\Veyon\plugins" mkdir "C:\Program Files\Veyon\plugins"',
            'copy /Y veyon-chat-plugin.dll "C:\Program Files\Veyon\plugins\"',
            'echo Done. Restart Veyon Master/Service.'
          )
          Set-Content -Path "release-package\install.bat" -Value $installScript -Encoding ASCII
          $readme = @(
            '# Veyon Chat Plugin - Windows (for Veyon 4.9.7)',
            '',
            '1) Run `install.bat` as Administrator',
            '2) Restart **Veyon Service** (clients) and **Veyon Master** (teacher)',
            '3) Open Veyon and verify the plugin appears under Plugins'
          )
          Set-Content -Path "release-package\README.txt" -Value $readme -Encoding UTF8
          Compress-Archive -Path "release-package\*" -DestinationPath "veyon-chat-plugin-windows.zip" -Force

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: veyon-chat-plugin-windows
          path: |
            release-package/veyon-chat-plugin.dll
            release-package/install.bat
            release-package/README.txt
            veyon-chat-plugin-windows.zip
          retention-days: 90
