name: Build Veyon Chat Plugin for Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup Qt (Alternative Method)
      shell: powershell
      run: |
        # Download and install Qt using aqtinstall (more reliable)
        python -m pip install --upgrade pip
        python -m pip install aqtinstall
        
        # Install Qt 5.15.2 for Windows MSVC 2019 64-bit
        python -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 -m qtmultimedia
        
        # Set Qt environment variables
        $QtPath = "$env:GITHUB_WORKSPACE\5.15.2\msvc2019_64"
        echo "Qt5_DIR=$QtPath\lib\cmake\Qt5" >> $env:GITHUB_ENV
        echo "$QtPath\bin" >> $env:GITHUB_PATH
        
        # Verify Qt installation
        if (Test-Path "$QtPath\bin\qmake.exe") {
          Write-Host "✅ Qt installed successfully at: $QtPath"
          & "$QtPath\bin\qmake.exe" -version
        } else {
          Write-Host "❌ Qt installation failed"
          exit 1
        }
        
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake
      shell: powershell
      run: |
        cd build
        
        # Use the Qt path from environment
        $QtDir = $env:Qt5_DIR
        Write-Host "Using Qt5_DIR: $QtDir"
        
        cmake -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_BUILD_TYPE=Release `
          -DQt5_DIR="$QtDir" `
          -DCMAKE_PREFIX_PATH="$env:GITHUB_WORKSPACE\5.15.2\msvc2019_64" `
          ..
      
    - name: Build plugin
      run: |
        cd build
        cmake --build . --config Release --parallel
        
    - name: Verify DLL creation
      shell: powershell
      run: |
        $dllPath = "build/Release/veyon-chat-plugin.dll"
        if (Test-Path $dllPath) {
          Write-Host "✅ DLL created successfully!"
          Get-Item $dllPath | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ DLL not found!"
          Write-Host "Checking build directory contents:"
          Get-ChildItem -Recurse build | Where-Object {$_.Extension -eq ".dll"}
          exit 1
        }
      
    - name: Create installation package
      shell: powershell
      run: |
        # Create release directory
        New-Item -ItemType Directory -Path "release-package" -Force
        
        # Copy DLL
        Copy-Item "build/Release/veyon-chat-plugin.dll" "release-package/"
        
        # Create installation batch script
        $installScript = @'
@echo off
echo Installing Veyon Chat Plugin...
if not exist "C:\Program Files\Veyon\plugins" mkdir "C:\Program Files\Veyon\plugins"
copy veyon-chat-plugin.dll "C:\Program Files\Veyon\plugins\"
echo Plugin installed successfully!
echo Please restart Veyon Master and Service.
pause
'@
        
        $installScript | Out-File -FilePath "release-package/install.bat" -Encoding ASCII
        
        # Create README file
        $readmeContent = @'
# Veyon Chat Plugin - Windows Release

## Installation Instructions

1. Extract all files to a folder
2. Right-click 'install.bat' and select 'Run as administrator'
3. Restart Veyon Master application
4. Press F10 to open chat window

## Files Included

- veyon-chat-plugin.dll - The plugin file
- install.bat - Automated installation script

## Requirements

- Veyon 4.9.7 installed
- Windows 10/11
- Administrator privileges for installation

For support, visit: https://github.com/PhotographerSeth/Veyon
'@
        
        $readmeContent | Out-File -FilePath "release-package/README.txt" -Encoding UTF8
        
        # Create ZIP package
        Compress-Archive -Path "release-package/*" -DestinationPath "veyon-chat-plugin-windows.zip" -Force
        
    - name: Upload plugin artifacts
      uses: actions/upload-artifact@v4
      with:
        name: veyon-chat-plugin-windows
        path: |
          release-package/veyon-chat-plugin.dll
          release-package/install.bat
          release-package/README.txt
        retention-days: 90
        
    - name: Upload complete package
      uses: actions/upload-artifact@v4
      with:
        name: veyon-chat-plugin-complete-package
        path: veyon-chat-plugin-windows.zip
        retention-days: 90
